config/routes.rb
Rails.application.routes.draw do
  root 'epicenter#feed'

  get 'user_profile' => 'epicenter#show_user'

  post 'now_following' => 'epicenter#now_following'

  post 'unfollow' => 'epicenter#unfollow'

  devise_for :users
  resources :tweets
  

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
  
  validates :message, presence: true, length: {maximum: 140, too_long: "A tweet is only 140 max. Everybody knows that!"}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :tweets
  
  validates :username, presence: true, uniqueness: true
  
  serialize :following, Array
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters

    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit({ roles: [] }, :email, :password, :password_confirmation, 
      :name, :username, :bio, :location, :following) }

    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, 
      :current_password, :name, :username, :bio, :location, :following) }

  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
    before_filter :authenticate_user!

  def feed
    @following_tweets = []
    
    @tweets = Tweet.all
    
    @tweets.each do |tweet|
      current_user.following.each do |f|
        @following_tweets.push(tweet)
      end
    end
  end

  def show_user
    @user = User.find(params[:id])
  end

  def now_following
    @user = User.find(params[:follow_id])
    
    current_user.following.push(params[:follow_id].to_i)
    
    current_user.save
  end

  def unfollow
    @user = User.find(params[:unfollow_id])
    
    current_user.following.delete(params[:unfollow_id].to_i)
    
    if current_user.following.size == 0
      current_user.following = [nil]
    end
    
    current_user.save
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    
    before_action :set_tweet, only: [:show, :edit, :update, :destroy]
    
    before_filter :authenticate_user!
    
    def index
        @t = Tweet.all
    end
    
    def show
    end
    
    def new
        @tweet = Tweet.new
    end
    
    def edit
    end
    
    def create
        @tweet = Tweet.new(tweet_params)

        respond_to do |format|
            if @tweet.save
                format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
            else
                format.html { render :new }
            end
        end
    end
    
    def update
        respond_to do |format|
            if @tweet.update(tweet_params)
                format.html { redirect_to @tweet, notice: 'Post was successfully updated.' }
            else
                format.html { render :edit }
            end
        end
    end
    
    def destroy
      @tweet.destroy
        respond_to do |format|
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
        end
    end
    
    private
    
        def set_tweet
            @tweet = Tweet.find(params[:id])
        end

        def tweet_params
            params.require(:tweet).permit(:message, :user_id)
        end
        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/epicenter/feed.html.erb
<h1>Your Twitter Feed</h1>
<p>Hello <%= current_user.name %>!</p>
<p>Here is what your friends are saying:</p>

<div>
    <% @following_tweets.each do |f| %>
    <div>
        <p><%= f.message %></p>
        <p><strong><em><%= f.user.username %></em></strong></p>
    </div>
    <% end %>
</div>

app/views/epicenter/now_following.html.erb
<p>You are now following: <%= @user.username %></p>

app/views/epicenter/show_user.html.erb
<script>
    $(document).ready(function() {
        $("#unfollow-btn").hover(function() {
            $(this).removeClass("btn-custom");
            $(this).addClass("btn-danger");
            $(this).prop("value","Unfollow");
        }, function() {
            $(this).prop("value","Following");
            $(this).removeClass("btn-danger");
            $(this).addClass("btn-custom");
        });
    });
</script>
<h1><%= @user.username %></h1>
<h3><%= @user.location %></h3>
<h3><%= @user.bio %></h3>

<div class="row">
    <% @user.tweets.each do |tweet| %>
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <p><%= tweet.message %></p>
            </div>
        </div>
    </div>
    <% end %>
</div>
<div>
<% if current_user.id != @user.id %>
    <% if current_user.following.include?(@user.id) %>
    <%= form_tag('/unfollow') do %>
    <div class="cant-see-me">
        <%= number_field_tag :unfollow_id, @user.id %>
    </div>
    <%= submit_tag "Following", class: "btn btn-custom", id: "unfollow-btn" %>
    <% end %>
    </div>
<% else %>
<div>
    <%= form_tag('/now_following') do %>
    <span class="invisible">
        <%= number_field_tag :follow_id, @user.id %>
    </span><br />
    <%= submit_tag "Follow", class:"btn btn-custom" %>
    <% end %>
</div>
    <% end %>
<% end %>

app/views/epicenter/unfollow.html.erb
<p>You're not following <%= @user.username %> anymore. *sad face*</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitter</title>
  <%= javascript_include_tag "https://code.jquery.com/jquery-2.1.4.min.js" %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>

 <% if user_signed_in? %>
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to "Tweets", tweets_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><%= link_to "New Tweet", new_tweet_path %></li>
      </ul>

      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete%>
</li>
          <li> <%= link_to "Edit Profile", edit_user_registration_path %></li>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <% else %>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-brand" %>
    </div>
  </div><!-- /.container-fluid -->
</nav>
      <% end %>

<div class="jumbotron">
  <h1>Twitters</h1>
</div>

<div class="container">
<%= yield %>

</div>
</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
<% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_field :message %>
  </div>

  <div class="field cant-see-me">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id, value: current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit "Tweet!", class: "btn btn-custom" %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet, class: "btn btn-custom" %> |
<%= link_to 'Back', tweets_path, class: "btn btn-custom" %>

app/views/tweets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Twitters!</h1>

<table class="table">
  <thead>
    <tr>
      <th>Message</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @t.each do |x| %>
      <tr>
        <td><%= x.message %></td>
        <td> <%= link_to x.user.username, user_profile_path(id: x.user.id) %> </td>        
        <td><%= link_to 'Show', x, class: "btn btn-custom"%></td>
        <td><%= link_to 'Edit', edit_tweet_path(x), class: "btn btn-custom" %></td>
        <td><%= link_to 'Destroy', x, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-custom" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tweet', new_tweet_path, class: "btn btn-custom" %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path, class: 'btn btn-custom' %>

app/views/tweets/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <strong>Message:</strong>
  <%= @tweet.message %>
</p>

<p>
<strong>User:</strong>
  <%= link_to @tweet.user.username, user_profile_path(id: @tweet.user.id)  %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet), class: "btn btn-custom" %> |
<%= link_to 'Back', tweets_path, class: "btn btn-custom" %>